### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by mabezdek** [contributte/doctrine-dbal#52]
Hello,

is possible to configure multiple connections (for two databases)?

Thank you.

**Comment by marten-cz** [comment]
Any plan for this?

**Comment by f3l1x** [comment]
Yes, there is.

**Comment by f3l1x** [comment]
Can you help me with that @marten-cz?

**Comment by marten-cz** [comment]
Was quickly looking into that. Not sure, but looked like it will not be just about configuration. Sure, can try.
