### ISSUE TITLE
Tracy panel crashes with queries containing regular expressions

### ISSUE THREAD

**Issue by servantales25** [contributte/doctrine-dbal#61]
If there's a question mark usages in query (because of regular expression) with similar usage to this `REGEXP_REPLACE(u.name, '^([^ ]+)(?: ([^\\(].+[^\\)]))?(?: \\((.+)\\))?$', '$2$1$3')`, then `vsprintf()` function call in **Logger\ProfileLogger** throws this warning 

> vsprintf(): Too few arguments

This is probably caused by sanitization of question marks (used in sql's regexp) replacing them by %s.

**Comment by matronator** [comment]
Having the same issue.

**Comment by f3l1x** [comment]
Resolved, use new version
