### ISSUE TITLE
Using `blob` as a column type causes `ProfilerLogger` to fail

### ISSUE THREAD

**Issue by dakur** [contributte/doctrine-dbal#71]
# Error message

`PDO::quote(): Argument #1 ($string) must be of type string, resource given` in [ProfilerLogger.php#L61](https://github.com/nettrine/dbal/blob/v0.8.0/src/Logger/ProfilerLogger.php#L61)

# Trace screenshot

![image](https://user-images.githubusercontent.com/9862581/176167657-2d819142-e1fa-4aa3-9763-2672383bea13.png)

# Problematic column

is annotated as follows:

```php
/**
 * @ORM\Column(type="blob")
 * @var resource
 */
private $stream;
```

# Workaround

is to disable tracy panel:

```neon
nettrine.dbal:
	debug:
		panel: false # %debugMode% # temporary disabled as otherwise ProfilerLogger complains on blob types
```

**Comment by f3l1x** [comment]
Resolved, use new version
