### ISSUE TITLE
Missing constant Connection::PARAM_ASCII_STR_ARRAY with doctrine/dbal:3.2

### ISSUE THREAD

**Issue by K0nias** [contributte/doctrine-dbal#72]
In nettrine/dbal:0.8.0 method \Nettrine\DBAL\Logger\ProfilerLogger::needsArrayParameterConversion use constant Connection::PARAM_ASCII_STR_ARRAY that was added in doctrine/dbal:3.3. So wtih doctrine/dbal:3.2 throws error

**Comment by f3l1x** [comment]
Solved via https://github.com/contributte/doctrine-dbal/commit/e5d38af256c05617c1387ecba8f04ec58c32447a

We requires doctrine >= 3.5
