### ISSUE TITLE
Configuration - setFilterSchemaAssetsExpression does not exist in doctrine\dbal 3.x

### ISSUE THREAD

**Issue by Gappa** [contributte/doctrine-dbal#75]
After updating to `doctrine\orm` 2.14.0 a warning message started to show:

- https://github.com/doctrine/orm/pull/10153/files#diff-7579891fde50fb7e38d285004486c0210492efdbdc00815a978e053ff3cb0017

```
[WARNING] Not passing the "--complete" option to "orm:schema-tool:update" is deprecated and will not be supported when using doctrine/dbal 4 
```

I started to dig around and found this configuration for `nettrine/dbal`:

``` neon
nettrine.dbal:
    configuration:
        filterSchemaAssetsExpression: <string>
```

Internally, it sets stuff up to call this method:

https://github.com/contributte/doctrine-dbal/blob/1aab0ae838f368339af52ff2c5a2aed2122df6d8/src/DI/DbalExtension.php#L139-L142

``` php
\Doctrine\DBAL\Configuration::setFilterSchemaAssetsExpression()
``` 

However, this method has been removed in  `doctrine\dbal` 3.x:

- https://github.com/doctrine/dbal/commit/5e7ceff857096e33195ab9b1255eea7664cafd08

That means it doesn't work for quite a long time - since nobody used this (me included), it went unnoticed.

I guess the only fix is to implement #57 and remove this from the configuration/extension, `doctrine\dbal` 2.x also supports the schemaFilter callable.

**Comment by juniwalk** [comment]
Implemented in https://github.com/contributte/doctrine-dbal/commit/cb448d2970f216153563581aa5d6ef2ab58fc668

**Comment by Gappa** [comment]
I finally got to this and found out that something is missing from the implementation mentioned - I made a PR (#79).

Closing this one :)
