### ISSUE TITLE
Release a version with PHP 8.2 support

### ISSUE THREAD

**Issue by hason-kosik** [contributte/doctrine-dbal#80]
Please, when will the new version with PHP 8.2 support be released?

**Comment by f3l1x** [comment]
Hi @hason-kosik, max one week. I am finishing testing on my projects.

**Comment by haltuf** [comment]
@f3l1x Do you possibly have example how to replace EventSubscriber (e.g. like [this one](https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/EventSubscriber/TranslatableEventSubscriber.php)) with Middleware?

It used to register itself, thanks to [these lines](https://github.com/contributte/doctrine-dbal/blob/cdd8a432de37bf6026f129fb5d5ad9bde4abeab6/src/DI/DbalExtension.php#L206-L216) probably, now it does not...

**Comment by f3l1x** [comment]
Hey @haltuf, thank you for pointing that. 

I've implement EventManager support (again). Can you test it? 

https://github.com/contributte/doctrine-dbal/commit/52b85b8fe5097a0ea90594ba48511c0e8d2abe03

**Comment by haltuf** [comment]
@f3l1x Thanks! It works now as before.

**Comment by haltuf** [comment]
@f3l1x Seems like schemaAssetsFilter changed its behaviour. Previously:

```
schemaAssetsFilter: PorovnavacZajezdu\Model\ORM\SchemaFilter::filter
```

with `public static function filter(string|AbstractAsset $assetName): bool`

Now it returns 

`Failed assertion #0 for item 'nettrine.dbal › configuration › schemaAssetsFilter' with value 'PorovnavacZa...`

Is it a bug, or feature?

**Comment by f3l1x** [comment]
It's a bug. Will repair.

**Comment by haltuf** [comment]
Sorry, did not notice you have edited your last comment (no futher notification). I have tested it now and the problem has been solved by this commit.

**Comment by f3l1x** [comment]
Good news. :-)

**Comment by haltuf** [comment]
Hi @f3l1x , I have trouble with sortable injected through [this package](https://contributte.org/packages/contributte/doctrine-extensions-atlantic18.html).

Trying to call:

`$rec = $this->em->getRepository(SuggestedTransformation::class);`

Versions 0.9@dev dbal+orm, cache 0.4, annotations 0.8 leads to the error message:

`This repository can be attached only to ORM sortable listener`

with failure in [here](https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/src/Sortable/Entity/Repository/SortableRepository.php#L59)

This is how dump of `$em->getEventManager()->getAllListeners()` looks like:

![obrazek](https://github.com/contributte/doctrine-dbal/assets/325759/d272429f-bde6-43d1-8053-d182df1de952)

In versions 0.8 dbal+orm, cache 0.3, annotations 0.7 it works just fine.

This is how dump of `$em->getEventManager()->getAllListeners()` looks like in these:

![obrazek](https://github.com/contributte/doctrine-dbal/assets/325759/23ee696a-e8cd-4842-a6b3-b080000d0ee3)

When updating from old (working) version to new (problematic) version, these are the packages that get updated:

`
Lock file operations: 0 installs, 4 updates, 0 removals
  - Upgrading nettrine/annotations (v0.7.0 => v0.8.1)
  - Upgrading nettrine/cache (v0.3.0 => v0.4.1)
  - Upgrading nettrine/dbal (v0.8.2 => dev-master 00c5783)
  - Upgrading nettrine/orm (v0.8.4 => dev-master 9e2cd91)
`

**Comment by haltuf** [comment]
@f3l1x Do you have idea, where I should be searching for the source of the problem? I can try to fix myself.

**Comment by f3l1x** [comment]
Thanks, I will take a look. `addServiceSubscriber` has special purpose to by lazy and not instance all subscribers at once.

**Comment by f3l1x** [comment]
Can you please take a look @haltuf https://github.com/contributte/doctrine-dbal/commit/5053516ade579534de3fb3b401f316a1049644f5 and try latest version?

**Comment by f3l1x** [comment]
Yes, it's empty. I must reimplement it, because there is no logger in DBAL anymore. I must use middlewares and custom classes.

**Comment by f3l1x** [comment]
Version 0.9.x is bumped. I work on 0.10.x with DBAL 4.2+ requirements and multi connection support. Closing here.

https://github.com/contributte/doctrine-dbal/commit/9996070f02c3f66a173f2e0af7d845af02b87f5c
