### ISSUE TITLE
Tracy doesn't show any SQL queries in bar

### ISSUE THREAD

**Issue by petrparolek** [contributte/doctrine-dbal#82]
Version: master 26b53be916586e87b772050f32986168e55f8e48

### Bug Description
Tracy doesn't show any SQL queries in bar

![obrazek](https://github.com/contributte/doctrine-dbal/assets/6066243/afb0aa03-f082-4fa2-a1da-b705da768061)

### Steps To Reproduce
Run sqls with doctrine

### Expected Behavior
showing every queries

### Possible Solution
N/A

**Comment by f3l1x** [comment]
Yep, I need to rewrite it using middlewares.

**Comment by petrparolek** [comment]
@f3l1x  Still not working in 0.9.0.

**Comment by f3l1x** [comment]
Should be implemented here https://github.com/contributte/doctrine-dbal/commit/de3f94a61e7cba5f315da500e9781084e7806a36, but now it's needed to updated ORM part. Stay tuned.
